on:
  pull_request:
    branches: [master,github-action]
  push:
    branches: [master,github-action]
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update action files
      uses: posener/goaction@v1
      with:
        name: luet-github-action
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        email: mudler@mocaccino.org
        desc: "Github Action for creating multi-node k3s clusters"
        install: "docker,wget,curl,jq,netcat-openbsd"
        icon: "box"
        color: purple
    - name: Generate
      uses: ./
      with:
        generate: true
    - name: "Check files were built"
      run: |
            cat token