name: Jumpbox

on:
  push:
concurrency: 
  group: jumpbox-${{ github.head_ref || github.ref }}-${{ github.repository }}
jobs:
  master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ip: "10.1.0.3/24"
            ip_addr: "10.1.0.3"
    steps:
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: server up
        env:
          EDGEVPN: ${{ secrets.EDGEVPN }}
          ADDRESS: ${{ matrix.ip }}
          IP: ${{ matrix.ip_addr }}
          MASTER: 10.1.0.20
        run: |
              source helpers.sh
              start_vpn
              start_jumpbox
              prepare_jumpbox
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
